### PR TITLE
Pin pymongo

### PR DESCRIPTION
**Pull request by eriktaubeneck**
@tleach this should fix the travis failure

### CODE REVIEW

**Comment by tleach** [comment]
@eriktaubeneck what failure?

**Comment by eriktaubeneck** [comment]
https://travis-ci.org/gamechanger/mongothon/builds/67225329

**Comment by eriktaubeneck** [comment]
seems pymongo 3.0 isn't compatible :disappointed:

**Comment by tleach** [comment]
booo :+1:

**Pull request merged**
